small tweaks in bash script

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -1,35 +1,34 @@
 #!/usr/bin/env bash
 
-# Synopsis:
-# Test the track's exercises.
-# 
-# At a minimum, this file must check if the example/exemplar solution of each 
-# Practice/Concept Exercise passes the exercise's tests.
-#
-# To check this, you usually have to (temporarily) replace the exercise's solution files
-# with its exemplar/example files.
-#
-# If your track uses skipped tests, make sure to (temporarily) enable these tests
-# before running the tests.
-#
-# The path to the solution/example/exemplar files can be found in the exercise's
-# .meta/config.json file, or possibly inferred from the exercise's directory name.
+RED=$(tput setaf 1)
+GREEN=$(tput setaf 2)
+prepath=tmp-exercises
 
-# Example:
-# ./bin/test
+cp -r exercises $prepath
+cd $prepath
 
-# Verify the Concept Exercises
-for concept_exercise_dir in ./exercises/concept/*/; do
-    if [ -d $concept_exercise_dir ]; then
-        echo "Checking $(basename "${concept_exercise_dir}") exercise..."
-        # TODO: run command to verify that the exemplar solution passes the tests
-    fi
+cnt=0
+for exercise in practice/*/ concept/*/; do
+  if [ -d "$exercise" ]; then
+    cd $exercise
+    printf "\n====================\nTESTING $exercise \n====================\n"
+
+    # copy reference solution into stub file in src/
+    cat .meta/reference.chpl > src/$(basename "${exercise}").chpl
+
+    # if test fails, increment failures counter
+    if ! mason test --show; then ((cnt++)); fi
+
+    cd -
+  fi
 done
 
-# Verify the Practice Exercises
-for practice_exercise_dir in ./exercises/practice/*/; do
-    if [ -d $practice_exercise_dir ]; then
-        echo "Checking $(basename "${practice_exercise_dir}") exercise..."
-        # TODO: run command to verify that the example solution passes the tests
-    fi
-done
+cd ..
+rm -rf $prepath
+
+if [ $cnt -gt 0 ]; then
+  printf "\n${RED}$cnt TESTS FAILED\n"
+  exit 1
+else
+  printf "\n${GREEN} ALL TESTS PASSED\n"
+fi
